### ISSUE TITLE
Run cargo deny in CI

### ISSUE THREAD

**Issue by djc** [memorysafety/ntpd-rs#16]
This helps check dependency licenses, security vulnerabilities and other stuff. Something like this:

https://github.com/InstantDomain/instant-distance/blob/main/.github/workflows/rust.yml#L79

**Comment by djc** [comment]
Here's a suitable default configuration:

```toml
targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
]

[licenses]
allow-osi-fsf-free = "either"
copyleft = "deny"
private = { ignore = true }
allow = ["MPL-2.0"]
```
